landingpage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('profile', views.profile, name='profile'),
    path('books', views.books, name='buku'),
    path('data', views.data, name='data'),
    #path('delete', views.delete, name='delete'),

]

ppwStartTDD/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('', include(('landingpage.urls','landingpage'),namespace='landingpage')),
    path('story10/', include('story10.urls')),
]

story10/urls.py
from  django.urls import path
from . import views

urlpatterns = [
    path('',views.formRegistrasi,name='formRegistrasi'),
    path('submit', views.submitForm, name='submit'),
    path('ajax/validate',views.validate_email,name='validate'),
    path('delete/<email>', views.delete_user_by_email, name='delete'),
    path('data/subscriber', views.json_subscriber, name='subscriber')
]

landingpage/models.py
from django.db import models

# Create your models here.

class ApaKabar(models.Model):
    status = models.CharField(max_length=300)

story10/models.py
from django.db import models

# Create your models here

class Registrasi(models.Model):
    nama = models.CharField(max_length=40)
    email = models.CharField(max_length=40)
    password = models.CharField(max_length=15)

    def as_dict(self):
        return {
            "friend_name": self.nama,
            "email": self.email,
        }

landingpage/forms.py
from django import forms
from django.db import models
from .models import ApaKabar
from django.forms import ModelForm

class statusForm(forms.ModelForm):

    class Meta:
        model = ApaKabar
        fields = ('status',)
        widgets = {
            'status': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bagaimana kabar Anda hari ini ?'}),
        }

story10/forms.py
from django import forms
from .models import Registrasi
from django.db import models



class FormRegis(forms.ModelForm):

    class Meta:
        model = Registrasi
        fields = ('nama', 'email', 'password')
        widgets = {
            'nama': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Masukan Nama Anda'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Masukan Email Anda', 'type': 'email'}),
            'password': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Masukan Password Anda', 'type': 'password'}),
        }

landingpage/views.py
from .models import ApaKabar
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render,redirect
from .forms import statusForm
import requests
import json

# Create your views here.



def index(request):
    data = ApaKabar.objects.all()
    form = statusForm()
    response = {'data': data, 'form': form}

    form = statusForm(request.POST)
    if request.method == "POST":
        form.save()
        return render(request, 'landingpage/landingpage.html',response)
    else:
        return render(request, 'landingpage/landingpage.html', response)

def profile(request):
    return render(request, 'landingpage/profile.html')

def books(request):
    return render(request, 'landingpage/Books.html')

def data(request):
    listBuku = requests.get('https://www.googleapis.com/books/v1/volumes?q=quilting')
    jsonBook = listBuku.json()
    return JsonResponse(jsonBook)

# def delete(request):
#     data = ApaKabar.objects.all().delete()
#     response = {'data' : data}
#     return redirect('home',response)

story10/views.py
from django.shortcuts import render,reverse,redirect
from django.http import JsonResponse,HttpResponse
from .models import Registrasi
from .forms import FormRegis
import itertools
from django.views.decorators.csrf import csrf_exempt

import  json
# Create your views here.


def formRegistrasi(request):
    form = FormRegis()
    return render(request,'story10/post.html', {'form' : form})

def submitForm(request):
    data = {'success':False}
    form = FormRegis(request.POST)
    if request.method == "POST":
        if form.is_valid():
            print('abc')
            form.save()
            data['success'] = True
            data1 = json.dumps(data)

        else:
            print(form.errors)
            data1 = json.dumps(data)
        return HttpResponse(data1, content_type='application/json')
    else : return redirect('formRegistrasi')


def validate_email(request):
    email = request.GET.get('email',None)
    data = {
        'is_taken': Registrasi.objects.filter(email=email).exists(),
        "test":email
    }

    return JsonResponse(data)

def delete_user_by_email(request,email=None):
    Registrasi.objects.filter(email=str(email)).delete()
    return HttpResponse('OK')

def json_subscriber(request):
    data = Registrasi.objects.all()
    userDict = [{'nama' : i.nama,'email': i.email} for i in data]
    return HttpResponse(json.dumps({'Subscriber': userDict}), content_type='application/json')

# def formRegistrasi(request):
#     form = FormRegis(request.POST)
#     if request.method == "POST":
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('formRegistrasi'))
#     else:
#         form = FormRegis()
#     return render(request,'story10/post.html', {'form' : form})

landingpage/templates/landingpage/Books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- jQuery !-->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>-->
    <!-- jQuery UI !-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <title>Story 9</title>

    <script>
        
        $( function () {
            var counter = 0;

            $.ajax({
                url: '/data',
                dataType : 'json',
                success:function(response){
                    var s = "";
                    var raw = response[("items")];
                    for(i = 0; i < raw.length; i++){
                        var index = '' + i;
                        var result = raw[index];

                        var title = result['volumeInfo']['title'];
                        var publisher = result['volumeInfo']['authors'];
                        var image = '"' + result['volumeInfo']['imageLinks']['thumbnail'] + '"';

                        s+='<tr>';
                        s+='<td style="vertical-align: middle !important; text-align: center">' + (i+1) + '</td>';
                        s+='<td style="vertical-align: middle !important;">' + '<img src=' + image +'>' + '</td>';
                        s+='<td style="vertical-align: middle !important;">' + title + '</td>';
                        s+='<td style="vertical-align: middle !important;">' + publisher + '</td>';
                        s+='<td style="vertical-align: middle !important; text-align: center">' + '<button class="btn star"" '  + '><i class="fa fa-star"></i></button>' + '</td>';
                        s+='</tr>';
                    }

                    $('#list').html(s);
            }});


            $('body').on('click', '.star', function () {
                var color = $( this ).css( "background-color" );
                var str = '';
                console.log(color);
                if(color ==='rgb(255, 255, 0)'){
                    counter--;
                    str = '<h1>Favorites : ' + counter + '</h1>';
                    $(this).css("background-color","rgb(221, 221, 221)");
                    $('#count').html(str);
                }
                else{
                    counter++;
                    str = '<h1>Favorites : ' + counter + '</h1>';
                    $(this).css("background-color","yellow");
                    $('#count').html(str);
                    // $('.btn:hover').css('background-color','gray');

                }
            });

            $('body').on('click', '.dropdown-item', function () {

                var menuSelceted = $(this).text();
                console.log(menuSelceted);

                $('.dropdown-item').css('background-color','white');
                $('.dropdown-item').css('color','black');
                $(this).css('background-color','#007bff');
                $(this).css('color','white');

                var link =  'https://www.googleapis.com/books/v1/volumes?q=' + menuSelceted;
                $.ajax({
                    url: link,
                    dataType : 'json',
                    success:function(response){
                        var s = "";
                        var raw = response[("items")];
                        for(i = 0; i < raw.length; i++){
                            var index = '' + i;
                            var result = raw[index];

                            var title = result['volumeInfo']['title'];
                            var publisher = result['volumeInfo']['authors'];
                            var image = '"' + result['volumeInfo']['imageLinks']['thumbnail'] + '"';

                            s+='<tr>';
                            s+='<td style="vertical-align: middle !important; text-align: center">' + (i+1) + '</td>';
                            s+='<td style="vertical-align: middle !important;">' + '<img src=' + image +'>' + '</td>';
                            s+='<td style="vertical-align: middle !important;">' + title + '</td>';
                            s+='<td style="vertical-align: middle !important;">' + publisher + '</td>';
                            s+='<td style="vertical-align: middle !important; text-align: center">' + '<button class="btn star"" '  + '><i class="fa fa-star"></i></button>' + '</td>';
                            s+='</tr>';
                        }

                        $('#list').html(s);
                    }});
            });





        })


    </script>


    <style>
        .btn {
            border: none;
            color: white;
            padding: 12px 16px;
            font-size: 16px;
            cursor: pointer;
        }

        /* Darker background on mouse-over */
        .star:hover {
            color: white;
            background-color: orange;
        }

    </style>
</head>
<body>
    <div class="container" style="margin-top: 3vh">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/profile">Profile</a>
            </li>
            <li class="nav-item">
                <a id="b" class="nav-link active" href="#">Books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/story10">Subscribe</a>
            </li>
        </ul>
    </div>



        <div class="container" >
            <div class="row" id="count" style="margin: 7vh">
                <h1>Favorites : 0</h1>
            </div>
        </div>

        <div class="container">
            <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    Genre
                </button>
                <div class="dropdown-menu">
                    <button class="dropdown-item" >Adobe Illustrator</button>
                    <button class="dropdown-item" >Quilting</button>
                    <button class="dropdown-item" >Harry Potter</button>
                </div>
            </div>
        </div>

        <table class=" container table table-striped" style="margin-top: 5vh;padding-right: 2vw">
            <thead>
            <tr>
                <th style="text-align: center">#</th>
                <th>Cover</th>
                <th>Title</th>
                <th>Author(s)</th>
                <th style="text-align: center">Favorites</th>
            </tr>
            </thead>


            <tbody id="list">

            </tbody>
        </table>


</body>
</html>

landingpage/templates/landingpage/landingpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Story 6</title>
</head>
<body>


    <div class="content container" style="margin-top: 3vh">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link active" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/profile">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/books">Books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/story10">Subscribe</a>
            </li>

        </ul>

        <div class="row" style="margin-top: 12vh">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                {% if user.is_authenticated %}
                <h2>Hello, {{ user.username }} apa kabar?</h2>
                {% endif %}
            </div>
            <div class="col-md-2"></div>


        </div>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <form method="POST" action="{% url 'landingpage:home' %}" class="form-group" >
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="save btn btn-default" name="submit" style="margin-top: 3vh">Save</button>
                </form>

                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Your Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in data %}
                    <tr>
                        <td>{{i.status}}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>


            </div>
            <div class="col-md-2"></div>
        </div>
    </div>

</body>
</html>`

landingpage/templates/landingpage/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Profil</title>
</head>
<body>

    <div class="content container" style="margin-top: 3vh">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="#">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/books">Books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/story10">Subscribe</a>
            </li>

        </ul>

        <div class="container">
            <div class="row" style="margin-top: 2vh">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <img src="https://s15.postimg.cc/csj0ae1qz/Webp.net-resizeimage.jpg" style="border-radius: 2vw">
                </div>
                <div class="col-md-12"></div>
            </div>
                <h1 id="nama">Faishal Ammar</h1>
                <h1 id="deskripsi">Tertarik pada dunia start up, desain, pemrograman dan fotografi </h1>
        </div>
    <div>
</body>
</html>

story10/templates/story10/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id" content="964248809008-ngn649mhgnminrfj23fr350lkt26ubv6.apps.googleusercontent.com">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Story 10</title>


    <style>
        .g-signin2{
            padding-top: 0px!important;
            padding-bottom: 0px!important;

        }
    </style>
</head>
<body>

    <div class="container" style="margin-top: 3vh">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/profile">Profile</a>
            </li>
            <li class="nav-item">
                <a id="b" class="nav-link" href="/books">Books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="/story10">Subscribe</a>
            </li>
            <li class="nav-item signout ">
                <a class="nav-link" style="margin-left: 12px" href="#" onclick="signOut();">Sign out</a>
            </li>

            <li class="nav-item Profile ">
                <a class="nav-link"></a>
            </li>

            <li class="nav-item signin">
                <a class="g-signin2 nav-link" data-onsuccess="onSignIn" ></a>
            </li>

        </ul>
    </div>

    <div class="container" style="margin-top: 5vh">
        <div class="container subscriber">
            <h1>Subscriber</h1>

            <table class=" container table table-striped" style="margin-top: 5vh;padding-right: 2vw">
                <thead>
                <tr>
                    <th style="text-align: center">#</th>
                    <th>Nama</th>
                    <th>Email</th>
                    <th>Unsubscribe</th>
                </tr>
                </thead>


                <tbody id="list">

                </tbody>
            </table>
            <button class="subscribe btn btn-primary" name="Subscriber" style="margin-top: 3vh;margin-bottom: 5vh">Subscribe</button>

        </div>
        <form method="POST" action="#" class="form-group" >
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="save btn btn-default" name="submit" style="margin-top: 3vh">Save</button>
        </form>
        <div class="alert alert-danger fade show" role="alert" style="margin-top: 2vh">
            <strong>Email sudah terdaftar.</strong> <br> Silahkan gunakan email yang lain
        </div>
        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 2vh">
             Subscribe berhasil. Terimakasih
        </div>
    </div>

    <!---------------------- Script -------------------------------------------------------------------------------------------------- -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script>
        $('.signout').hide()
        $('.Profile').hide();

        function onSignIn(googleUser) {
            $('.signout').show();
            var profile = googleUser.getBasicProfile();
            $('.signin').hide();
            $('.Profile').show();
            $('.Profile').html('<a class="nav-link">Selamat Datang, ' + profile.getName() + '</a>');
            console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
            console.log('Name: ' + profile.getName());
            console.log('Image URL: ' + profile.getImageUrl());
            console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.

            // The ID token you need to pass to your backend:
            var id_token = googleUser.getAuthResponse().id_token;
            console.log("ID Token: " + id_token);
        }

        function signOut() {
            var auth2 = gapi.auth2.getAuthInstance();
            $('.signin').show();
            $('.Profile').hide();

            auth2.signOut().then(function () {
                console.log('User signed out.');
            });
        }

        $( function () {
            $('.alert').hide();
            $('.form-group').hide();

            $('.subscribe').click(function() {
                $('.subscriber').slideUp(500);
                $('.form-group').delay(400).show(200);
            });

            // tombol unsubscribe ------------------------------------------------


            $('body').on('click', '.unsubscribe', function () {
                var email = $(this).attr('id');
                var link = "delete/" + email+"";
                var tr_deleted = 'tr_' + email;
                document.getElementById(tr_deleted).remove();
                $.ajax({
                    url:link,
                });
            });

            // Json data/subscriber ke table -------------------------------------

            $.ajax({
                url: '{% url "subscriber" %}',
                dataType : 'json',
                success:function(response){
                    var s = "";
                    console.log(response);
                    var raw = response["Subscriber"];
                    console.log(raw);
                    for(i = 0; i < raw.length; i++){
                        var index = '' + i;
                        var result = raw[index];

                        var nama = result['nama'];
                        var email = result['email'];

                        s+='<tr id=tr_'+ email + '>';
                        s+='<td style="vertical-align: middle !important; text-align: center">' + (i+1) + '</td>';;
                        s+='<td style="vertical-align: middle !important;">' + nama + '</td>';
                        s+='<td style="vertical-align: middle !important;">' + email + '</td>';
                        s+='<td <button id='+ email + ' class="unsubscribe btn btn-danger" name="Subscriber" style="margin-top: 3vh;margin-bottom: 5vh">unsubscribe</button>'
                        s+='</tr>';
                    }

                    $('#list').html(s);
                }});

            // validasi email sama apa engga -----------------------------------

            $('#id_email').change(function () {
                email = $(this).val();
                console.log($(this).val());
                $.ajax({
                    method: "GET",
                    url: '{% url "validate" %}',
                    data: {
                        'email': email
                    },
                    dataType: 'json',
                    success: function(data){
                        console.log(data);
                        console.log(data.test);
                        if(data.is_taken){
                            $('.save').attr('disabled','disabled');
                            $('.alert-danger').slideDown();
                            $('#id_email').after($('.alert-danger'));
                        }
                        else {
                            $('.alert-danger').slideUp();
                            $('.save').attr('disabled',null);
                        }
                    }
                })
            });
        });


        $(document).ready(function () {
            $('.form-group').on('submit', function(){
                var name = $('#id_nama');
                var email = $('#id_email');
                var password = $('#id_password');
                var data = {
                    'nama': name.val(),
                    'email': email.val(),
                    'password':password.val(),
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                };
                $.ajax({
                    method: 'POST',
                    url: '/story10/submit',
                    type: 'json',
                    data: data,
                    success: function (result) {
                        console.log('result : ' + result.success)
                        $('.alert-success').show(300).delay(1000).hide(300);
                        name.val('');
                        email.val('');
                        password.val('');

                    }
                })
                event.preventDefault();
            })
        })


    </script>
</body>
</html>

story10/templates/story10/test.html
<!DOCTYPE HTML>

<html lang="en">
    <meta charset="UTF-8">
<head>
    <style>

        .section1{
            background-image:url('http://i63.tinypic.com/xnryio.png');
            grid-area: left;
        }
        .section2{
            grid-area: right;
        }
        .grid-container{
        }
        .container2{
            left: 50%;
            top: 30vh
        }
        .signUp{
            background-color: #00aced;
            color: white;
            text-align: center;
            width: 140px;
        }
        .signIn{
            background-color: white;
            border : 2px;
            border-color: #1dcaff;
            color: #1dcaff;
            text-align: center;
            width: 140px;
        }
        .formulir{
            left: 50%;
            float:left;
            margin:6px;
        }
        .input-form{
            width: auto;
            float:left;
        }
        .login{
            border-color: #1dcaff;
            color: #1dcaff;
            border-radius: 50px;
        }
        .join{
            font-size:10px;
        }
    </style>
</head>

<Body>

<div class="grid-container">
    <div class="section1">

    </div>

    <div class="section2">
        <div class='container'>
            <form class='formulir'>
                <input class="input-form" placeholder="Phone, email or Username">Phone, email or Username</input>
                <input class="input-form" placeholder="Password">Password</input>
                <h2>forgot password?</h2>
                <button class="login">login</button>
            </form>
        </div>


        <div class='container2'>
            <img src='http://i64.tinypic.com/23quft.jpg'>
            <div class= "text">
                <h2>See What's the happening in </h2>
                <h2>the world right now</h2>
            </div>
            <h2 class='join'>Join Twitter Today</h2>
            <button class="signUp">Sign Up</button>
            <button class="signIn">Log in</button>
        </div>

    </div>

</div>

</Body>
</html>